### ISSUE TITLE
Query Parameters for PUT and DELETE

### ISSUE THREAD

**Issue by BigBlueHat** [micha/resty#20]
First, Resty is fabulous! :) Thanks for building it.

Second, it'd be great if it were possible to pass query parameters to PUT and DELETE methods. I'd really love to be able to put them inline with the URL (ex: /url?param=value&other=value), but being able to use -d or similar would be fine at this point. Perhaps an alternative scheme would be a -q switch that could take a string of query parameters:
-q "param=value&other=value"

This feature would make working with CouchDB a good bit easier given it's need for "rev=1-...." whenever PUT-ing or DELETE-ing documents or attachments. I'm getting around it now using -H "If-Match: 1-..." (the Etag-based solution), but there are likely other API's that aren't that flexible.

Thanks for considering this idea,
Benjamin

**Comment by dikshaSahni** [comment]
Is it possible to send Query params with PUT request in Java Rest API?

**Comment by AdrieanKhisbe** [comment]
@DevDik What Java rest api are you talking about, 
you're probably looking for https://github.com/beders/Resty :)
