### ISSUE TITLE
Allow default resty options

### ISSUE THREAD

**Issue by bbeck** [micha/resty#27]
I'd really like the ability to specify default resty options.  I'm lazy and in certain cases I would like to always be able to type URLs in the same way that I specify them in my browser.  For example I'd like the following scenario to work:

``` bash
$ resty http://localhost:8080
resty http://localhost:8080*

$ # This won't actually work...
$ GET '/jane?rev=1'
<some error from the server>

$ # Instead you need to do...
$ GET '/jane?rev=1' -Q
{ "_id": "jane", "active": "true", ... }

$ # Or you can do...
$ GET '/jane' -q 'rev=1'
{ "_id": "jane", "active": "true", ... }
```

Ideally you'd be able to tell resty when you specify the URI base (or perhaps through a configuration file in ~/.resty) that you want all GET commands to include resty's -Q option.  I'm not quite sure what the syntax should be for that though.  I'd be perfectly happy if it was buried inside of a config file somewhere and not available to be set via the command line during the URI base specification.

Think it's reasonable to add something like this?

**Comment by AdrieanKhisbe** [comment]
Has been implemented in a similar via than host defined options via the `resty` special host :)

**Comment by AdrieanKhisbe** [comment]
3.0 is gonna land soon, closing the issue
