### ISSUE TITLE
Current resty fails completely in zsh

### ISSUE THREAD

**Issue by snej** [micha/resty#38]
I just downloaded resty and it doesn't work at all for me with zsh:

```
$ . resty
$ resty 'http://localhost:4984'
http://localhost:4984*
$ GET /
curl: (3) <url> malformed
```

I've got zsh 4.3.11 on Mac OS X 10.8.2.

Unfortunately my shell-scripting fu is very low, so I don't know how to go about debugging this. No doubt it's some arcane difference in quoting between bash and zsh...

**Comment by AdrieanKhisbe** [comment]
I didn't have any problem trying it on zsh 5.0.2, but have no idea if it comes from change in `zsh`, or changes that occur on `resty`

**Comment by AdrieanKhisbe** [comment]
closing to do lack of activity
