### ISSUE TITLE
Performance in cygwin

### ISSUE THREAD

**Issue by gv0tch0** [micha/resty#39]
Resty is 2 orders of magnitude slower then POCurl on cygwin. A request that takes 7 millis to get back using curl takes 700 millis with resty (same exact options).

(Will provide traces tomorrow...)

**Comment by AdrieanKhisbe** [comment]
Hey @gv0tch0, I know it's a bit late, but could you provide us your traces?

**Comment by AdrieanKhisbe** [comment]
closing so far because no details provided.
