### ISSUE TITLE
DELETE request with a payload?

### ISSUE THREAD

**Issue by pv7721** [micha/resty#46]
Hello,

I know that as this is vaguely touched in the HTTP spec, most REST tools are very touchy about this subject: some disallow completely such behaviour, and resty seems to ignore any payload given along a DELETE request. So is this an issue or works as designed? Thanks!

**Comment by AdrieanKhisbe** [comment]
Reading SO comments, make sense to me to enable to do this with `resty`.

Then one could be able to send a body if I need and I server user it.

What is your mind on this?
(If okey, I'll add this feature)

**Comment by AdrieanKhisbe** [comment]
Next major version of resty will support it. (implemented in the refactor branch)

Otherwise for use case like , it's better I think to make use of the Header than a payload.

**Comment by rhlsthrm** [comment]
I would like to use this functionality as well. Can this be released?

**Comment by AdrieanKhisbe** [comment]
@rhlsthrm It would need me to refresh and complete the refactor I started two years ago.
but this may happens :)

**Comment by AdrieanKhisbe** [comment]
this should normally land with #50 pr
