### ISSUE TITLE
How to assign output to variable

### ISSUE THREAD

**Issue by amitaibu** [micha/resty#54]
I assumed doing ``VAR=$(GET /foo)`` would work, but it doesn't. How can it be done?

**Comment by AdrieanKhisbe** [comment]
hey @amitaibu, did you get an error?

You should try to code protect the subcommand: `VAR="$(GET /foo)"`.
Tell me if it fix your problem

**Comment by amitaibu** [comment]
Worked, thanks. Closed in favor of #55
