### ISSUE TITLE
Please add a LICENSE

### ISSUE THREAD

**Issue by jones77** [micha/resty#62]
Enterprise and commercial users would probably appreciate this.

eg Something from here: http://choosealicense.com/licenses/ and copy-paste it into a LICENSE / LICENSE.md / LICENSE.txt file in root.

Thanks!

**Comment by AdrieanKhisbe** [comment]
@micha, I would go for MIT Licence, any objection?

**Comment by AdrieanKhisbe** [comment]
request timeout, let's go for MIT
