### ISSUE TITLE
windows?

### ISSUE THREAD

**Issue by ramstein74** [micha/resty#65]
does not work on windows right?

**Comment by soyo42** [comment]
I guess there is a fair chance that resty works under cygwin or msys.

**Comment by goposky** [comment]
It works but u need to have a bunch of non-default cygwin commands installed such as curl, etc..

**Comment by AdrieanKhisbe** [comment]
@ramstein74 does it answer the question?
if so we shall close =)

**Comment by AdrieanKhisbe** [comment]
closing since no output, and answer given
