### ISSUE TITLE
parameters in $configdir are ignored - expansion fail

### ISSUE THREAD

**Issue by soyo42** [micha/resty#69]
Preconfigured parameters for host and method in $configdir are ignored. Reason is failing variable expansion due to apostrophes around expression:
`.. |grep '^$method' | ..`

**Comment by soyo42** [comment]
Fix in #67.

**Comment by AdrieanKhisbe** [comment]
@soyo42 Just merged your fix. 
can you test it and confirm it work? :)
then closing the issue

**Comment by soyo42** [comment]
Hi Adriean,
I confirm - it works now. Thank you.

**Comment by AdrieanKhisbe** [comment]
you're welcome :)
