### ISSUE TITLE
Sourcing resty with OPTIONS

### ISSUE THREAD

**Issue by josdotso** [micha/resty#70]
Hi folks.

I see in the docs:

```
source resty [-W] [remote]              # load functions into shell
```

But is this also possible?:

```
source resty [-W] [remote] [OPTIONS]       # load functions into shell
```

Thanks,
Joshua

**Comment by AdrieanKhisbe** [comment]
@josdotso After verification this is possible.
At the end of the script that load the functions, resty is called with all his arguments:

```
resty "$@" >/dev/null 2>&1
```

**Comment by AdrieanKhisbe** [comment]
(shall I close the issue?)
