### ISSUE TITLE
Publish version 2.3

### ISSUE THREAD

**Issue by roele** [micha/resty#74]
Since the last release is almost 6 years old and several issues have been addressed meanwhile it would be beneficial to have a new release available. Package managers such as homebrew still point to version 2.2 which does not contain PATH for example (also see #73).

**Comment by AdrieanKhisbe** [comment]
Noted. Might do this in the coming days

**Comment by AdrieanKhisbe** [comment]
@roele In progress: https://github.com/Homebrew/homebrew-core/pull/18857#partial-pull-merging :)

**Comment by AdrieanKhisbe** [comment]
@roele Done and available on `brew`
announced on reddit: https://www.reddit.com/r/commandline/comments/7a4wq6/new_release_of_the_rest_client_resty/
