### ISSUE TITLE
Problems on Mac

### ISSUE THREAD

**Issue by vidstige** [micha/resty#79]
Love this, use it all the time at work. However, at home I mostly use my trust mac laptop and resty is struggling. See excerpt below
```bash
resty http://localhost:5000
http://localhost:5000*
muskot:badges vidstige$ GET /
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
-bash: : No such file or directory
cat: : No such file or directory
cat: : No such file or directory

```

Bash version:
```
$ bash --version
GNU bash, version 3.2.53(1)-release (x86_64-apple-darwin13)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by AdrieanKhisbe** [comment]
Hello @vidstige, thanks for your report.
Which version of resty are you using, and how did you install it?

(I'm personnaly using a mac and don't have a problem with that)
Have you tried on newer version of bash? (v4)

**Comment by vidstige** [comment]
Cannot reproduce on my new mac anymore, works fine now. I installed it by curling the file, if I remember correctly.
